### ISSUE TITLE
local write to existing folder fails

### ISSUE THREAD

**Issue by slsriehl** [bypasslane/template-to-pdf#4]
I can't speak to aws uploading (great feature which I will eventually use!)...

But when I specify filePath for local write, the write fails if the directory already exists.  If you're using fs & promises, should be a simple fix to check if the folder exists and bypass the mkdir if so.  Sorry I don't have time right now to look at your code and point out the line.

**Comment by slsriehl** [comment]
something like

//promise library
//promisify fs

return fs.mkdirAsync(pathToUserDir)
.catch((error) => {
  if(!error || error.errno == -17) {
    return //write stream async
  } else {
    console.log(util.inspect(error) + 'there was a problem creating the folder')
    return Promise.reject(error);
  }
})
.then...

**Comment by txssseal** [comment]
thank you, will look into this.

**Comment by txssseal** [comment]
@slsriehl this should be fixed in https://github.com/bypasslane/template-to-pdf/pull/2
